import type { Product } from "@/types/product";

/**
 * Fallback local enquanto a tabela Supabase é criada/populada.
 * Inclui storage_key relativos ao R2 (sem nome do bucket).
 * Ordem: Halftone (originais + Vol.2) → demais (Graphic Tee).
 */
export const fallbackProducts: Product[] = [
  {
    id: "1",
    name: "Coleção Animes - HALFTONE",
    slug: "animes",
    quantity: 132,
    style: "Halftone",
    price: 29.9,
    compareAtPrice: 59.9,
    soldCount: 112,
    image: "/products/animes.webp",
    gallery: [
      "/products/animes.webp",
      "/products/animes-2.webp",
      "/products/animes-3.webp",
      "/products/animes-4.webp",
    ],
    storageProvider: "r2",
    storageKey: "Animes/ANIMES 132.rar",
  },
  {
    id: "2",
    name: "Coleção Filmes - HALFTONE",
    slug: "filmes",
    quantity: 119,
    style: "Halftone",
    price: 22.9,
    compareAtPrice: 39.9,
    soldCount: 67,
    image: "/products/filmes.webp",
    gallery: [
      "/products/filmes.webp",
      "/products/filmes-2.webp",
      "/products/filmes-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "Filmes/filmes 119.rar",
  },
  {
    id: "3",
    name: "Coleção Futebol - HALFTONE",
    slug: "futebol",
    quantity: 128,
    style: "Halftone",
    price: 22.9,
    compareAtPrice: 39.9,
    soldCount: 94,
    image: "/products/futebol.webp",
    gallery: [
      "/products/futebol.webp",
      "/products/futebol-2.webp",
      "/products/futebol-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "Futebol/FUTEBOL 128.rar",
  },
  {
    id: "4",
    name: "Coleção Jogos - HALFTONE",
    slug: "jogos",
    quantity: 112,
    style: "Halftone",
    price: 29.9,
    compareAtPrice: 59.9,
    soldCount: 51,
    image: "/products/jogos.webp",
    gallery: [
      "/products/jogos.webp",
      "/products/jogos-2.webp",
      "/products/jogos-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "Games/PERSONAGENS JOGOS 112.rar",
  },
  {
    id: "5",
    name: "Coleção Religião - HALFTONE",
    slug: "religiao",
    quantity: 112,
    style: "Halftone",
    price: 29.9,
    compareAtPrice: 59.9,
    soldCount: 78,
    image: "/products/religiao.webp",
    gallery: [
      "/products/religiao.webp",
      "/products/religiao-2.webp",
      "/products/religiao-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "Religião/RELIGIÃO 112.rar",
  },
  {
    id: "6",
    name: "Coleção Rock - HALFTONE",
    slug: "rock",
    quantity: 183,
    style: "Halftone",
    price: 22.9,
    compareAtPrice: 39.9,
    soldCount: 103,
    image: "/products/rock.webp",
    gallery: [
      "/products/rock.webp",
      "/products/rock-2.webp",
      "/products/rock-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "Rock/rock 183.rar",
  },
  {
    id: "7",
    name: "Coleção Streetwear - HALFTONE",
    slug: "streetwear",
    quantity: 123,
    style: "Halftone",
    price: 29.9,
    compareAtPrice: 59.9,
    soldCount: 59,
    image: "/products/streetwear.webp",
    gallery: [
      "/products/streetwear.webp",
      "/products/streetwear-2.webp",
      "/products/streetwear-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "Streetwear/STREETWEAR 123.rar",
  },
  {
    id: "8",
    name: "Coleção Animes Vol. 2 - HALFTONE",
    slug: "animesvol2",
    quantity: 162,
    style: "Halftone",
    price: 24.9,
    compareAtPrice: 49.9,
    soldCount: 91,
    image: "/products/animesvol2.webp",
    gallery: [
      "/products/animesvol2.webp",
      "/products/animesvol2-2.webp",
      "/products/animesvol2-3.webp",
      "/products/animesvol2-4.webp",
    ],
    storageProvider: "r2",
    storageKey: "Animes vol 2/HALFTONE-006.rar",
  },
  {
    id: "9",
    name: "Coleção Animes Lendas - EDITÁVEIS",
    slug: "animeslendas",
    quantity: 120,
    style: "Graphic Tee",
    price: 29.9,
    compareAtPrice: 59.9,
    soldCount: 110,
    image: "/products/animeslendas.webp",
    gallery: [
      "/products/animeslendas.webp",
      "/products/animeslendas-2.webp",
      "/products/animeslendas-3.webp",
      "/products/animeslendas-4.webp",
    ],
    storageProvider: "r2",
    storageKey: "Animes Lendas Shonen/ANIMES LENDAS SHONEN 120.rar",
  },
  {
    id: "10",
    name: "Coleção Teddy Bear - PNG",
    slug: "teddybear",
    quantity: 100,
    style: "Graphic Tee",
    price: 19.9,
    compareAtPrice: 24.9,
    soldCount: 42,
    image: "/products/teddybear.webp",
    gallery: [
      "/products/teddybear.webp",
      "/products/teddybear-2.webp",
      "/products/teddybear-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "TEDDY BEAR/TEDDY BEAR 100.rar",
  },
  {
    id: "11",
    name: "Coleção Japanese Samurai - PNG",
    slug: "samurai",
    quantity: 104,
    style: "Graphic Tee",
    price: 19.9,
    compareAtPrice: 24.9,
    soldCount: 29,
    image: "/products/samurai.webp",
    gallery: [
      "/products/samurai.webp",
      "/products/samurai-2.webp",
      "/products/samurai-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "JAPANESE SAMURAIS/SAMURAIS 104.rar",
  },
  {
    id: "12",
    name: "Coleção Angels - PNG",
    slug: "anjos",
    quantity: 85,
    style: "Graphic Tee",
    price: 17.9,
    compareAtPrice: 22.9,
    soldCount: 21,
    image: "/products/anjos.webp",
    gallery: [
      "/products/anjos.webp",
      "/products/anjos-2.webp",
      "/products/anjos-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "ANGELS/ANJOS 85.rar",
  },
  {
    id: "13",
    name: "Coleção Hip Hop - PNG",
    slug: "hiphop",
    quantity: 126,
    style: "Graphic Tee",
    price: 19.9,
    compareAtPrice: 24.9,
    soldCount: 27,
    image: "/products/hiphop.webp",
    gallery: [
      "/products/hiphop.webp",
      "/products/hiphop-2.webp",
      "/products/hiphop-3.webp",
    ],
    storageProvider: "r2",
    storageKey: "HIP HOP/HIP HOP 126.rar",
  },
];
